# Generated by Django 3.0.8 on 2020-08-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='cloudpanel.Product'),
        ),
    ]
