# Generated by Django 3.0.8 on 2020-08-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudpanel', '0002_auto_20200807_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cloudpanel.Shop'),
        ),
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cloudpanel.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cloudpanel.Category'),
        ),
    ]
